name: Bookstore API Automation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test
        run: mvn clean verify

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-test-report

      - name: Checkout GitHub Pages with previous Allure reports
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages-report
          path: gh-pages-dir

      - name: Copy README.md to gh-pages-dir
        run: cp target/allure-test-report/* gh-pages-dir/

      - name: Generate Allure test report
        uses: andgineer/allure-report@v3.6
        id: allure-report
        if: always()
        with:
          allure-results: allure-results
          website: gh-pages-dir
          reports-site-path: target

      - name: Publish Allure test report
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ always() && (steps.allure-report.outcome == 'success') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}